import pkg from '../package.json' assert { type: 'json' }
import { Inter } from "next/font/google"

import NavBar from './components/html/navbar/navbar-index'
import Footer from "./components/html/footer/footer-index"

import "./globals.css"

// import type { Metadata } from "next";

type Props = {
  children: React.ReactNode
};

const inter = Inter({ subsets: ["latin"] });
/*

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const icons = [
  {
    rel: "icon",
    sizes: "29x29",
    href: "/favicons/Icon-29@2x.png",
  },
  {
    rel: "icon",
    sizes: "40x40",
    href: "/favicons/Icon-40@2x.png",
  },
  {
    rel: "icon",
    sizes: "44x44",
    href: "/favicons/Icon-44@2x.png",
  },
  {
    rel: "icon",
    sizes: "50x50",
    href: "/favicons/Icon-50@2x.png",
  },
  {
    rel: "icon",
    sizes: "86x86",
    href: "/favicons/Icon-86@2x.png",
  }
];
 */
export default function RootLayout({ children }: Props) {

  return (
    <html suppressHydrationWarning={true} lang="en">
      <head>
        <meta charSet="UTF-8" />
        <title>Site Title</title>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="robots" content="index, follow" />
        <meta name="googlebot" content="index, follow" />
        <meta name="google" content="notranslate" />
        <meta name="theme-color" content="#317EFB" />
        <meta name="generator" content="Globy Solutions Tech" />
        <meta name="description" content={pkg.description} />
        <link rel="icon" type="image/svg+xml" href="/vercel.svg" style={{ height: 'auto', width: 'auto' }} />
        <link rel="sitemap" type="application/xml" href="/sitemap-index.xml" />
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="'https://twitter.com/" />
        <meta property="twitter:title" content={pkg.name} />
        <meta property="twitter:description" content={pkg.description} />
        <meta property="twitter:image" content="'https://twitter.com/" />
        <meta property="og:title" content={pkg.name} />
        <meta property="og:type" content="website" />
        <meta property="og:description" content={pkg.description} />
        <meta property="og:image" content={pkg.name} />
        <meta property="og:url" content={pkg.homepage} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content={pkg.name} />
        <meta name="twitter:creator" content={pkg.name} />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="canonical" href={pkg.homepage} />
        <link rel="manifest" href="/manifest.webmanifest" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <script src="/registerSW.js" async />
        <script src="/color_theme.js" defer />
      </head>
      <body className={inter.className}>
        <header>
          <NavBar />
        </header>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
